language: rust
rust:
  - stable

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - cargo test --verbose --features="volatile_fallback"
  - cargo test --verbose --release --features="volatile_fallback"
  - cargo test --verbose --features "volatile_fallback,trace"
  - cargo test --verbose --release --features "volatile_fallback,trace"